### PR TITLE
Feature/#161 autoscroll w2g

### LINKED ISSUE #161: Watch2Gether: Auto-scroll to next episode
For the host of a watch2gether session the episode list should automatically scroll to the first unseen episode when you have to choose the episode. Especially on shows with longer episode lists it can be really annoying if you have to scroll there by yourself each time. 

image

### PR DESCRIPTION
**Pull request by Serraniel**
Some small examples:
large window non-scrollable result list:
https://user-images.githubusercontent.com/8461282/107266356-b1034000-6a45-11eb-9a28-5e8d06fdd3c3.mp4

large window all episodes seen:
https://user-images.githubusercontent.com/8461282/107266511-ee67cd80-6a45-11eb-87d7-155ff75c586e.mp4

large window scrollable result list:
https://user-images.githubusercontent.com/8461282/107266431-cd06e180-6a45-11eb-86d2-503873ea633d.mp4

large window very large result list:
https://user-images.githubusercontent.com/8461282/107266486-e314a200-6a45-11eb-895c-5f45a4c7b852.mp4

small window non-scrollable result list:
https://user-images.githubusercontent.com/8461282/107266584-03dcf780-6a46-11eb-9935-bd0c0da2ab96.mp4

small window scrollable result list:
https://user-images.githubusercontent.com/8461282/107266597-0a6b6f00-6a46-11eb-9fb8-6a525d37fa2e.mp4

### CODE REVIEW

**Comment by Serraniel** [comment]
I just will add us both as reviewers as we both worked on this now :P

**Comment by Serraniel** [comment]
> I just will add us both as reviewers as we both worked on this now :P

Okay, I cannot set myself as reviewer....

**Comment by Serraniel** [comment]
To check:

- [x] clicking completed episodes in w2g
- [x] how often is the observer triggered

**Comment by Serraniel** [comment]
> To check:
> 
> * [x]  clicking completed episodes in w2g
> * [x]  how often is the observer triggered

The first task has been fixed. As side effect the observer has been optimized so it is less triggered.

**Comment by Serraniel** [comment]
@kaffem ready for review 👋

**Review by kaffem — APPROVED** [review]

**Pull request merged**
